// pages/Report.jsx — Final Interview Report Page
import { useEffect, useState } from 'react'
import { useParams, Link } from 'react-router-dom'
import { reportService } from '../services/reportService'
import toast from 'react-hot-toast'

export default function Report() {
  const { id } = useParams()
  const [report, setReport]   = useState(null)
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    reportService.get(id)
      .then(({ data }) => setReport(data))
      .catch(() => toast.error('Could not load report'))
      .finally(() => setLoading(false))
  }, [id])

  const ScoreRing = ({ label, score, color }) => (
    <div className="text-center">
      <div className={`w-16 h-16 rounded-full flex items-center justify-center mx-auto mb-2 font-bold text-lg ${color}`}>
        {score}%
      </div>
      <p className="text-xs text-gray-500">{label}</p>
    </div>
  )

  if (loading) return (
    <div className="min-h-screen flex items-center justify-center">
      <div className="text-gray-500">Loading report...</div>
    </div>
  )

  if (!report) return (
    <div className="min-h-screen flex items-center justify-center">
      <div className="text-center">
        <p className="text-gray-500 mb-4">Report not found</p>
        <Link to="/dashboard" className="btn-primary">Back to Dashboard</Link>
      </div>
    </div>
  )

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Header */}
      <div className="bg-ibm-blue text-white px-6 py-8">
        <div className="max-w-3xl mx-auto text-center">
          <h1 className="text-2xl font-bold mb-1">Interview Performance Report</h1>
          <p className="opacity-80 text-sm">Generated by IBM Granite AI</p>
          <div className="mt-4">
            <span className="text-5xl font-bold">{Math.round(report.overall_score)}%</span>
            <p className="text-sm opacity-80 mt-1">Overall Score</p>
          </div>
        </div>
      </div>

      <div className="max-w-3xl mx-auto px-4 py-8 space-y-6">
        {/* Score Breakdown */}
        <div className="card">
          <h2 className="font-bold text-gray-900 mb-6">Score Breakdown</h2>
          <div className="grid grid-cols-3 md:grid-cols-5 gap-4">
            <ScoreRing label="Technical"     score={Math.round(report.technical_score)}    color="bg-blue-100 text-blue-700" />
            <ScoreRing label="Communication" score={Math.round(report.communication_score)} color="bg-purple-100 text-purple-700" />
            <ScoreRing label="Behavioral"    score={Math.round(report.behavioral_score)}    color="bg-green-100 text-green-700" />
            <ScoreRing label="HR"            score={Math.round(report.hr_score)}            color="bg-yellow-100 text-yellow-700" />
            <ScoreRing label="Confidence"    score={Math.round(report.confidence_score)}    color="bg-red-100 text-red-700" />
          </div>
          {/* Readiness bar */}
          <div className="mt-6">
            <div className="flex justify-between text-sm mb-1">
              <span className="font-medium text-gray-700">Interview Readiness</span>
              <span className="font-bold text-ibm-blue">{Math.round(report.readiness_percentage)}%</span>
            </div>
            <div className="w-full bg-gray-200 rounded-full h-3">
              <div
                className="bg-ibm-blue h-3 rounded-full transition-all"
                style={{ width: `${report.readiness_percentage}%` }}
              />
            </div>
          </div>
        </div>

        {/* Strengths & Weaknesses */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div className="card">
            <h3 className="font-bold text-green-700 mb-3">Strengths</h3>
            {report.strengths.length > 0 ? report.strengths.map((s, i) => (
              <p key={i} className="text-sm text-gray-700 py-1 flex gap-2">
                <span className="text-green-500 font-bold">+</span>{s}
              </p>
            )) : <p className="text-sm text-gray-400">No data yet</p>}
          </div>
          <div className="card">
            <h3 className="font-bold text-red-600 mb-3">Areas to Improve</h3>
            {report.weaknesses.length > 0 ? report.weaknesses.map((w, i) => (
              <p key={i} className="text-sm text-gray-700 py-1 flex gap-2">
                <span className="text-red-400 font-bold">!</span>{w}
              </p>
            )) : <p className="text-sm text-gray-400">No data yet</p>}
          </div>
        </div>

        {/* Topics to Study */}
        {report.topics_to_improve?.length > 0 && (
          <div className="card">
            <h3 className="font-bold text-gray-900 mb-3">Topics to Study</h3>
            <div className="flex flex-wrap gap-2">
              {report.topics_to_improve.map((t, i) => (
                <span key={i} className="px-3 py-1 bg-orange-100 text-orange-700 text-sm rounded-full">{t}</span>
              ))}
            </div>
          </div>
        )}

        {/* Summary */}
        {report.summary && (
          <div className="card bg-blue-50 border-blue-200">
            <h3 className="font-bold text-ibm-blue mb-2">AI Summary</h3>
            <p className="text-sm text-gray-700 leading-relaxed">{report.summary}</p>
          </div>
        )}

        {/* Actions */}
        <div className="flex gap-4">
          <Link to="/dashboard" className="btn-secondary flex-1 text-center">
            Back to Dashboard
          </Link>
          <Link to="/upload" className="btn-primary flex-1 text-center">
            New Interview
          </Link>
        </div>
      </div>
    </div>
  )
}
